name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: npx semantic-release

      - name: Build project
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Set up SSH for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/github_key
          chmod 600 ~/.ssh/github_key
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_key

      - name: Transfer files to server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/github_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/sadmin/GameMonetaWebAppClient
            rm -rf dist/* 
          EOF
          scp -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_PORT }} -i ~/.ssh/github_key -r dist/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/sadmin/GameMonetaWebAppClient/dist
